### PR TITLE
Support testing against different versions

### PR DESCRIPTION
**Pull request by casz**
Thanks to @bturner suggestion 👍

### CODE REVIEW

**Comment by casz** [comment]
Using matrix since it gives a better view in Travis
image

**Comment by casz** [comment]
Merging since green built

**Comment by casz** [comment]
@bturner where would I report that quiet mode (-q) does not log integration tests result (it.bitbucket). I see that as a bug since surefire does show results in log.

**Comment by bturner** [comment]
@casz It's got to be something with the Failsafe plugin (a similar plugin to Surefire, but targeting integration tests instead of unit tests), or Maven itself. As far as I'm aware we don't have any real control over it.

That said, I'm not sure what you're seeing, because as far as I can tell all the tests are present:

```
$ mvn clean install -q --batch-mode

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running nl.topicus.bitbucket.api.HttpClientFactoryTest
2017-08-21 11:58:23,447 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1191654595{STOPPING,8<=8<=10,i=0,q=5} Couldn't stop Thread[qtp1191654595-33,5,]
2017-08-21 11:58:23,450 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1191654595{STOPPING,8<=8<=10,i=0,q=5} Couldn't stop Thread[qtp1191654595-34,5,]
2017-08-21 11:58:23,453 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp50699452{STOPPING,8<=8<=10,i=7,q=6} Couldn't stop Thread[qtp50699452-24,5,]
2017-08-21 11:58:23,453 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp50699452{STOPPING,8<=8<=10,i=0,q=5} Couldn't stop Thread[qtp50699452-25,5,]
2017-08-21 11:58:23,481 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1489933928{STOPPING,8<=8<=10,i=6,q=6} Couldn't stop Thread[qtp1489933928-54,5,]
2017-08-21 11:58:23,481 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1489933928{STOPPING,8<=8<=10,i=1,q=5} Couldn't stop Thread[qtp1489933928-55,5,]
2017-08-21 11:58:23,481 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1489933928{STOPPING,8<=8<=10,i=0,q=5} Couldn't stop Thread[qtp1489933928-64,5,]
2017-08-21 11:58:23,482 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1186339926{STOPPING,8<=8<=10,i=7,q=6} Couldn't stop Thread[qtp1186339926-45,5,]
2017-08-21 11:58:23,482 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1186339926{STOPPING,8<=8<=10,i=3,q=6} Couldn't stop Thread[qtp1186339926-46,5,]
2017-08-21 11:58:23,482 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1186339926{STOPPING,8<=8<=10,i=0,q=5} Couldn't stop Thread[qtp1186339926-51,5,]
2017-08-21 11:58:23,482 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1186339926{STOPPING,8<=8<=10,i=0,q=5} Couldn't stop Thread[qtp1186339926-66,5,]
2017-08-21 11:58:23,500 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1234586997{STOPPING,8<=8<=10,i=6,q=6} Couldn't stop Thread[qtp1234586997-77,5,]
2017-08-21 11:58:23,501 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1234586997{STOPPING,8<=8<=10,i=0,q=5} Couldn't stop Thread[qtp1234586997-78,5,]
2017-08-21 11:58:23,501 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1234586997{STOPPING,8<=8<=10,i=0,q=5} Couldn't stop Thread[qtp1234586997-86,5,]
2017-08-21 11:58:23,502 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1690101810{STOPPING,8<=8<=10,i=7,q=6} Couldn't stop Thread[qtp1690101810-68,5,]
2017-08-21 11:58:23,502 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1690101810{STOPPING,8<=8<=10,i=1,q=5} Couldn't stop Thread[qtp1690101810-69,5,]
2017-08-21 11:58:23,502 WARN  [main] w.o.e.j.util.thread.QueuedThreadPool qtp1690101810{STOPPING,8<=8<=10,i=0,q=5} Couldn't stop Thread[qtp1690101810-88,5,]
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.642 sec
Running nl.topicus.bitbucket.persistence.WebHookConfigurationDaoTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.47 sec

Results :

Tests run: 13, Failures: 0, Errors: 0, Skipped: 0


-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.nl.topicus.bitbucket.WebhookResourceTest
2017-08-21 12:01:20,740 INFO  [main] c.a.bitbucket.rule.RepeatRule testGetWebhooksForNonexistentProject(it.nl.topicus.bitbucket.WebhookResourceTest): Test has run 1 time.
2017-08-21 12:01:20,813 INFO  [main] c.a.bitbucket.rule.RepeatRule testRemoveWebhookWithNonexistentId(it.nl.topicus.bitbucket.WebhookResourceTest): Test has run 1 time.
2017-08-21 12:01:20,881 INFO  [main] c.a.bitbucket.rule.RepeatRule testGetWebhooksForNonexistentRepository(it.nl.topicus.bitbucket.WebhookResourceTest): Test has run 1 time.
2017-08-21 12:01:20,942 INFO  [main] c.a.bitbucket.rule.RepeatRule testGetWebhooksWithNoneConfigured(it.nl.topicus.bitbucket.WebhookResourceTest): Test has run 1 time.
2017-08-21 12:01:21,509 INFO  [main] c.a.bitbucket.rule.RepeatRule testCrudWebhook(it.nl.topicus.bitbucket.WebhookResourceTest): Test has run 1 time.
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.538 sec

Results :

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0
```

That's all the output I'd expect to see.

**Comment by casz** [comment]
@bturner your correct, I must be going blind...

**Comment by bturner** [comment]
With how it's structured it's pretty easy to overlook, I think. I'm glad there's nothing amiss after all, because trying to sort out what "layer" in the build it's at wouldn't have been much fun.

**Pull request merged**
