### PR TITLE
Fix create and update API verbs while keeping backwards compatibility

### PR DESCRIPTION
**Pull request by esmaras**

### CODE REVIEW

**Comment by casz** [comment]
@esmaras 
you might want to look into fixing your git user.email config 😅 
or set up an email alias on your GitHub account 🥇 
to get proper credit for your commits 🏆 
https://help.github.com/articles/adding-an-email-address-to-your-github-account/
https://help.github.com/articles/setting-your-commit-email-address-in-git
then to amend your commits: https://stackoverflow.com/a/3042512

**Comment by esmaras** [comment]
I will do that and I will add some documentation in the README to detail how to use the API. Is there anywhere else that documentation can be included as well?

**Comment by casz** [comment]
I think a MD or ADOC format is fine perhaps a docs folder in the git repo will do.

**Comment by esmaras** [comment]
@casz I added an API.md at the root level. Please let me know if it looks ok or if there need to be some changes. If there is someone else that needs to review then please let them know as well. I don't want to add documentation that is incomplete or insufficient.

**Comment by esmaras** [comment]
@casz When can this be merged? I am not sure of the protocol and obviously don't have permission.

**Comment by casz** [comment]
@esmaras would you mind updating the readme to a readme.md and link to API.md ? :)

**Comment by esmaras** [comment]
@casz done

**Pull request merged**
