### PR TITLE
send pull request event on participant approved event

### PR DESCRIPTION
**Pull request by casz**
Decided to rework #23 on a new PR since, I wanted to keep the original work to compare against.

I have added `Action` to `BitbucketServerPullRequestEvent` instead of using the new `BitbucketServerPullRequestActivityEvent`

With the main implementation of listeners using [IgnoreUnknown](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/e220b43404aca15574c7a9be3724a40587093414/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/events/BitbucketServerPullRequestEvent.java#L32) and listening for certain [types](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookEventType.java#L34-L57).

@shmish111 I have changed the key to [`pullrequest:approved`](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Approved) instead of `pullrequest:activity`
You may have to adapt your listener to it.

actor was missing on the original approved event on #23 so you only got the message that it was approved, but not who did it.

Setting the [Action](https://developer.atlassian.com/static/javadoc/bitbucket-server/4.6.2/api/reference/com/atlassian/bitbucket/pull/PullRequestAction.html) also opens up for easier opening up to more event listeners.

Another reason to reuse Pull Request Event

The `BitbucketServerPullRequestParticipantApprovedEvent.java` class in PR #23 was unused so I removed that, did not add any value.

We are almost following the [`pullrequest:approved`](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Approved) Cloud webhook API.
@Eernie would you suggest I rework it to follow exactly that?

Current payload

```
{
    "actor": {
        "username": "user",
        "displayName": "User"
    },
    "pullrequest": {
        "id": "2",
        "title": "Add some more text",
        "link": "http://localhost:7990/bitbucket/projects/PROJECT_1/repos/rep_1/pull-requests/2",
        "authorLogin": "Administrator",
        "fromRef": {
            "repository": {
                "scmId": "git",
                "project": {
                    "key": "PROJECT_1",
                    "name": "Project 1"
                },
                "slug": "rep_1",
                "links": {
                    "self": [
                        {
                            "href": "http://localhost:7990/bitbucket/projects/PROJECT_1/repos/rep_1/browse"
                        }
                    ]
                },
                "public": false,
                "owner": {
                    "username": "PROJECT_1",
                    "displayName": "PROJECT_1"
                },
                "fullName": "PROJECT_1/rep_1",
                "ownerName": "PROJECT_1"
            },
            "commit": {
                "message": null,
                "date": null,
                "hash": "96679164f20970581848c1b7ae2620473f269444",
                "authorTimestamp": 0
            },
            "branch": {
                "name": "test",
                "rawNode": "96679164f20970581848c1b7ae2620473f269444"
            }
        },
        "toRef": {
            "repository": {
                "scmId": "git",
                "project": {
                    "key": "PROJECT_1",
                    "name": "Project 1"
                },
                "slug": "rep_1",
                "links": {
                    "self": [
                        {
                            "href": "http://localhost:7990/bitbucket/projects/PROJECT_1/repos/rep_1/browse"
                        }
                    ]
                },
                "public": false,
                "owner": {
                    "username": "PROJECT_1",
                    "displayName": "PROJECT_1"
                },
                "fullName": "PROJECT_1/rep_1",
                "ownerName": "PROJECT_1"
            },
            "commit": {
                "message": null,
                "date": null,
                "hash": "0a943a29376f2336b78312d99e65da17048951db",
                "authorTimestamp": 0
            },
            "branch": {
                "name": "master",
                "rawNode": "0a943a29376f2336b78312d99e65da17048951db"
            }
        }
    },
    "repository": {
        "scmId": "git",
        "project": {
            "key": "PROJECT_1",
            "name": "Project 1"
        },
        "slug": "rep_1",
        "links": {
            "self": [
                {
                    "href": "http://localhost:7990/bitbucket/projects/PROJECT_1/repos/rep_1/browse"
                }
            ]
        },
        "public": false,
        "owner": {
            "username": "PROJECT_1",
            "displayName": "PROJECT_1"
        },
        "fullName": "PROJECT_1/rep_1",
        "ownerName": "PROJECT_1"
    },
    "action": {
        "action": "APPROVED"
    }
}
```

### CODE REVIEW

**Comment by casz** [comment]
in https://github.com/Eernie/bitbucket-webhooks-plugin/pull/64/commits/48e2c34869a9cb5292fa780925087cf1b8f0794c I wanted to avoid this
```
"action": {
  "action": "APPROVED"
}
```
reduced to
```
"action": "APPROVED"
```

**Comment by casz** [comment]
The `repo:push`, `pullrequest:created`, `pullrequest:updated`, `pullrequest:fulfilled`, `pullrequest:rejected`
Remain unchanged and they follow cloud pretty closely based on #25 comments
They have ignore unknown meaning they will ignore any new attributes we add to pull request event.
So no needed changes.
Was not planning on changes those either.

If anything I was planning on aligning comment, approved.
Perhaps look at adding other events but put them as disabled.

**Comment by casz** [comment]
If we are to follow the bitbucket cloud.
The missing events as for pull request events that needs to be corrected are `approval removed`, `approved`, `comment created`, `comment updated`, `comment deleted`

Build status events needs to be corrected too. With `Build status created` and `Build status updated`

**Comment by casz** [comment]
Bitbucket has the proper events to support most of them.
[`PullRequestCommentAddedEvent`](https://developer.atlassian.com/static/javadoc/bitbucket-server/4.6.2/api/reference/com/atlassian/bitbucket/event/pull/PullRequestCommentAddedEvent.html)
[`PullRequestCommentDeletedEvent`](https://developer.atlassian.com/static/javadoc/bitbucket-server/4.6.2/api/reference/com/atlassian/bitbucket/event/pull/PullRequestCommentDeletedEvent.html)
[`PullRequestCommentEditedEvent`](https://developer.atlassian.com/static/javadoc/bitbucket-server/4.6.2/api/reference/com/atlassian/bitbucket/event/pull/PullRequestCommentEditedEvent.html)

Don't think we should deal with [`PullRequestCommentRepliedEvent`](https://developer.atlassian.com/static/javadoc/bitbucket-server/4.6.2/api/reference/com/atlassian/bitbucket/event/pull/PullRequestCommentRepliedEvent.html)

Build status created and build status updated is hard.
Since it only has an event for [`BuildStatusSetEvent`](https://developer.atlassian.com/static/javadoc/bitbucket-server/4.6.2/build-api/reference/com/atlassian/bitbucket/build/BuildStatusSetEvent.html)
So perhaps just mirror build status updated or created

**Comment by Eernie** [comment]
Ok, so what do you want to do? Its fine by me as is, and we can tackle the cloud events a later time or we can do it now.

**Comment by casz** [comment]
I think it's better to correct it now, to be inline.
I'll have a look at it during the weekend :)

**Comment by casz** [comment]
@bturner perhaps you could provide some inside into bitbucket 5.4's builtin webhook. Could we perhaps look at following the same event payloads structure. So they are aligned and both compatible with Jenkins for instance?

**Comment by shmish111** [comment]
Any update on this recently?

**Comment by casz** [comment]
sadly, I got stuck on waiting for a reply 😐 I'll try and get around to it again 👍

**Comment by shmish111** [comment]
bump again @casz it seems that the plugin has a lot of updates and fixes and so I really want to upgrade

**Comment by casz** [comment]
@shmish111 I am sorry, I just never had a chance to sit down and actually do the fix. I can't promise anything. You are welcome to submit a pull request, I will happily review it.

**Comment by shmish111** [comment]
is what you've done here still relevant? I haven't looked at this for ages but I can take a look at your PR here if that makes sense?

**Comment by casz** [comment]
Just tried to align payload and use the [`pullrequest:approved`](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Approved) key

**Pull request closed without merging**
