### PR TITLE
Use less expensive canMerge

### PR DESCRIPTION
**Pull request by casz**
Here's the original PR suggest to bturner's fork: https://github.com/bturner/bitbucket-webhooks-plugin/pull/1

Edit: rebased onto master, so ready for merge 👍 
Should be merged after #57

### CODE REVIEW

**Comment by casz** [comment]
As @bturner explained it, this won't drop support for older installation, it will just use a newer source to compile against.

See this post by @bturner
https://github.com/Eernie/bitbucket-webhooks-plugin/pull/55#discussion_r133552790

**Comment by casz** [comment]
The travis build is failing on canMerge haven been removed in version 5.

So just need to figure out a way to get around that.

**Comment by casz** [comment]
@Eernie my best answer is to remove `- atlas-mvn clean install --batch-mode -Dbitbucket.version=5.2.2` from travis file.
https://github.com/Eernie/bitbucket-webhooks-plugin/blob/master/.travis.yml#L21

Java compiler is not as clever as other compilers when it comes to conditional compiltation.

**Comment by abishek3876** [comment]
I think you can update the pom file to compile targeting a single version but test on multiple versions.

**Comment by casz** [comment]
I think @bturner said it best: https://github.com/bturner/bitbucket-webhooks-plugin/pull/1#issuecomment-322951374

**Comment by bturner** [comment]
I've been thinking about this, because I'd really like for us to have our cake (use `tryMerge` where possible) and eat it too (be able to test on all the versions). Turns out, it's actually pretty simple to make that happen. I just needed to change up how I specify the versions a little bit so that I set the plugin to _compile_ against one version and _test_ against another.

Here's a patch:

```
diff --git a/.travis.yml b/.travis.yml
index 16c62b8..a9a184c 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -17,8 +17,9 @@ install:
     - atlas-mvn -q org.apache.maven.plugins:maven-dependency-plugin:resolve-plugins --batch-mode

 script:
-  - atlas-mvn clean install --batch-mode -Dbitbucket.version=4.10.2
-  - atlas-mvn clean install --batch-mode -Dbitbucket.version=5.2.2
+  - atlas-mvn clean install --batch-mode -Dbitbucket.test.version=4.6.4
+  - atlas-mvn clean install --batch-mode -Dbitbucket.test.version=4.10.2
+  - atlas-mvn clean install --batch-mode -Dbitbucket.test.version=5.3.0

 cache:
 # Caching is not allowed for 'sudo: required' builds.
diff --git a/pom.xml b/pom.xml
index cf11d7c..2278c09 100644
--- a/pom.xml
+++ b/pom.xml
@@ -20,7 +20,7 @@
             <dependency>
                 <groupId>com.atlassian.bitbucket.server</groupId>
                 <artifactId>bitbucket-parent</artifactId>
-                <version>${bitbucket.version}</version>
+                <version>${bitbucket.api.version}</version>
                 <type>pom</type>
                 <scope>import</scope>
             </dependency>
@@ -172,8 +172,8 @@
                         <product>
                             <id>bitbucket</id>
                             <instanceId>bitbucket</instanceId>
-                            <version>${bitbucket.version}</version>
-                            <dataVersion>${bitbucket.data.version}</dataVersion>
+                            <version>${bitbucket.test.version}</version>
+                            <dataVersion>${bitbucket.test.version}</dataVersion>
                         </product>
                     </products>
                     <instructions>
@@ -323,8 +323,8 @@
         <!-- This key is used to keep the consistency between the key in atlassian-plugin.xml and the key to generate bundle. -->
         <atlassian.plugin.key>${project.groupId}.${project.artifactId}</atlassian.plugin.key>
         <atlassian.spring.scanner.version>1.2.13</atlassian.spring.scanner.version>
-        <bitbucket.version>4.10.2</bitbucket.version>
-        <bitbucket.data.version>${bitbucket.version}</bitbucket.data.version>
+        <bitbucket.api.version>4.10.2</bitbucket.api.version>
+        <bitbucket.test.version>${bitbucket.api.version}</bitbucket.test.version>
     </properties>

     <licenses>
```

(If you don't want to test 4.6.4 in Travis, feel free to ditch that line. I just figured it part of the goal was to retain 4.6 compatibility, it wouldn't hurt to test it.)

I've manually run this locally with `-Dbitbucket.test.version=4.6.4` and `-Dbitbucket.test.version=5.3.0` and it works fine on both.

**Comment by casz** [comment]
And it worked 👍

**Pull request merged**
